'use strict';
const STORAGE='mainframe-mission-v1';
let storageOK=true, saved=null;
try { saved=localStorage.getItem(STORAGE); } catch {storageOK=false;}
let state=Game.restore(saved,SECTORS), response=[], feedback=null, view=state.started?'game':'intro', audioContext;
const $=s=>document.querySelector(s);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const allTasks=()=>SECTORS.flatMap(s=>s.tasks);
const current=()=>SECTORS[state.sector].tasks[state.task];
const done=()=>allTasks().filter(t=>state.solved[t.id]).length;
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state));}catch{storageOK=false;}}
function tone(success){if(!state.sound)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.frequency.value=success?660:180;gain.gain.setValueAtTime(.045,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.2);oscillator.start();oscillator.stop(audioContext.currentTime+.2);}catch{}}
function scene(boss=false){return `<div class="station-art ${boss?'boss-art':''}" aria-hidden="true"><div class="orbital-ring ring-one"></div><div class="orbital-ring ring-two"></div><span class="star s1"></span><span class="star s2"></span><span class="star s3"></span><div class="core"><div class="core-inner">${boss?'N':'⌘'}<small>${boss?'NULL':'NIS · 01'}</small></div></div><div class="satellite satellite-one"></div><div class="satellite satellite-two"></div><div class="art-label label-one">${boss?'CORRUPTED LOGIC':'ORBITAL RESEARCH STATION'}</div><div class="art-label label-two">${boss?'BREAK THE CLAIMS':'SIGNAL DETECTED · 01'}</div><div class="scanline"></div></div>`;}
function intro(){return `<main id="main" class="intro" tabindex="-1"><div class="hero"><div class="hero-copy"><div class="eyebrow"><span class="dot"></span> INCOMING TRANSMISSION / REVISION MISSION</div><h1>Escape the<br><span>Mainframe.</span></h1><p class="lead">The station is locked. The evidence is corrupted.<br>Only your ICT knowledge can get the crew home.</p><p class="story">A rogue intelligence called <strong>NULL</strong> has taken control. Explore five sectors, restore the access keys and defeat its misleading claims in the core.</p><div class="button-row"><button class="primary" id="start">${state.started?'Continue mission':'Enter the station'} <span>↗</span></button>${state.finished?'<button id="view-report">Mission report</button>':''}</div><div class="mission-meta"><span>◷ <b>25–30 min</b><small>Suggested, never timed</small></span><span>◈ <b>5 sectors + boss</b><small>18 knowledge challenges</small></span><span>↻ <b>Retry. Learn. Unlock.</b><small>Keyboard & touch friendly</small></span></div></div>${scene()}</div><section class="briefing"><div><span class="eyebrow">MISSION BRIEF</span><h2>Knowledge is your access key.</h2></div><div><h3>01 / Investigate</h3><p>Inspect the room’s evidence. Find what NULL has missed.</p></div><div><h3>02 / Restore</h3><p>Connect records, rebuild a pipeline and choose your sources.</p></div><div><h3>03 / Escape</h3><p>Break the final claims. Take a personal revision report with you.</p></div></section><p class="privacy-note">No names. No accounts. Progress saves only in this browser. On shared devices, clear it after your session.</p></main>`;}
function map(){return `<aside class="map" aria-label="Station sectors"><div class="map-top"><span class="eyebrow">STATION MAP</span><span>${done()}/18</span></div><div class="sector-list">${SECTORS.map((s,i)=>{const unlocked=Game.unlocked(SECTORS,state,i), complete=s.tasks.every(t=>state.solved[t.id]);return `<button class="sector ${i===state.sector?'active':''} ${complete?'complete':''}" data-sector="${i}" ${unlocked?'':'disabled'} ${i===state.sector?'aria-current="step"':''} style="--sector-colour:${s.colour}"><span class="sector-icon">${complete?'✓':s.icon}</span><span><small>${i===5?'FINAL BOSS':'SECTOR 0'+(i+1)}</small>${s.name}</span><span class="sector-end">${complete?'KEY':unlocked?'→':'LOCKED'}</span></button>`;}).join('')}</div><div class="inventory"><span class="eyebrow">ACCESS KEYS</span><div class="keys">${SECTORS.slice(0,5).map((s,i)=>`<span class="key ${s.tasks.every(t=>state.solved[t.id])?'earned':''}" title="${s.key}: ${s.tasks.every(t=>state.solved[t.id])?'restored':'locked'}">${s.tasks.every(t=>state.solved[t.id])?'◆':'◇'}</span>`).join('')}</div><p>Restore all five keys to unlock the NULL Core.</p></div><div class="save-state">${storageOK?'● Progress saved on this device':'⚠ Storage unavailable. Keep this page open.'}</div><button id="report" class="text-button">View learning report ↗</button></aside>`;}
function controls(task){
  const locked=!!state.solved[task.id];
  if(task.type==='match')return `<div class="match-list">${task.rows.map((row,i)=>`<div class="match-row"><label for="wire-${i}"><span class="row-number">${String(i+1).padStart(2,'0')}</span>${escapeHTML(row)}</label><select id="wire-${i}" data-match="${i}" ${locked?'disabled':''}><option value="">Choose connection…</option>${task.choices.map(v=>`<option value="${escapeHTML(v)}" ${response[i]===v?'selected':''}>${escapeHTML(v)}</option>`).join('')}</select></div>`).join('')}</div>`;
  if(task.type==='number')return `<label class="number-label" for="number-answer">Mean temperature (°C)</label><input id="number-answer" type="number" inputmode="decimal" step="any" autocomplete="off" placeholder="Enter your answer" value="${escapeHTML(response||'')}" ${locked?'disabled':''}>`;
  if(task.type==='order')return `<div class="pipeline" aria-label="Your chosen sequence">${[0,1,2,3].map((_,i)=>`<div class="pipeline-slot"><span>${i+1}</span>${response[i]===undefined?'<em>Empty stage</em>':escapeHTML(task.options[response[i]])}</div>`).join('')}</div><div class="order-cards">${task.options.map((op,i)=>`<button data-order="${i}" ${locked||response.includes(i)?'disabled':''}>＋ ${escapeHTML(op)}</button>`).join('')}</div><button class="text-button" id="undo" ${locked||!response.length?'disabled':''}>↶ Undo last stage</button>`;
  return `<fieldset class="options"><legend class="sr-only">${task.type==='multi'?'Select two answers':'Choose one answer'}</legend>${task.options.map((op,i)=>`<label class="option ${response.includes(i)?'selected':''}"><input type="${task.type==='multi'?'checkbox':'radio'}" name="answer" value="${i}" ${response.includes(i)?'checked':''} ${locked?'disabled':''}><span class="option-marker">${String.fromCharCode(65+i)}</span><span>${escapeHTML(op)}</span></label>`).join('')}</fieldset>`;
}
function game(){const sector=SECTORS[state.sector],task=current(),solved=state.solved[task.id];return `<main id="main" class="game-layout" tabindex="-1">${map()}<section class="mission" style="--accent:${sector.colour}"><div class="mission-heading"><div><span class="eyebrow">${state.sector===5?'FINAL ENCOUNTER':'SECTOR 0'+(state.sector+1)} / ${sector.key}</span><h1>${sector.name}</h1><p>${sector.desc}</p></div><div class="xp"><strong>${Game.xp(SECTORS,state)}</strong><span>MISSION XP</span></div></div><div class="room-view ${state.sector===5?'danger-room':''}"><div class="room-grid"></div><div class="room-device"><span>${sector.icon}</span><small>${state.sector===5?'NULL ONLINE':'TERMINAL '+(state.task+1)}</small></div><div class="room-message"><span class="eyebrow">${state.sector===5?'HOSTILE TRANSMISSION':'CREW COMMUNICATION'}</span><p>${state.sector===5?'“You cannot escape my logic.”':state.solved[task.id]?'Access restored. The crew is one step closer.':'“Check the evidence. NULL is counting on assumptions.”'}</p></div><div class="room-platform"></div><div class="room-player"><div class="visor"></div></div><span class="room-coordinate">DECK ${state.sector+1} · GRID ${state.task+1}C</span></div><nav class="task-tabs" aria-label="Sector challenges">${sector.tasks.map((t,i)=>`<button data-task="${i}" ${i>0&&!state.solved[sector.tasks[i-1].id]?'disabled':''} ${i===state.task?'aria-current="step"':''}><span>${state.solved[t.id]?'✓':i+1}</span>${state.sector===5?'Shield':'Terminal'} ${i+1}</button>`).join('')}</nav><article class="puzzle"><div class="puzzle-header"><span class="eyebrow">${task.type==='match'?'CONNECT':task.type==='order'?'SEQUENCE':task.type==='multi'?'SELECT TWO':task.type==='number'?'CALCULATE':'DECIDE'}</span><button class="command" id="command">${task.command} ⓘ</button></div><h2 id="puzzle-title">${task.title}</h2><p class="brief">${task.brief}</p><details class="evidence" ${state.inspected[task.id]?'open':''}><summary>⌕ Inspect the evidence <span>${task.evidence.length} records</span></summary><ul>${task.evidence.map(e=>`<li>${escapeHTML(e)}</li>`).join('')}</ul></details><div id="controls">${controls(task)}</div><div id="feedback" role="status" aria-live="polite">${solved?`<div class="feedback success"><strong>✓ ${state.sector===5?'Shield broken':'Access granted'}</strong><p>${task.why}</p></div>`:feedback?`<div class="feedback retry"><strong>Signal mismatch. Investigate again.</strong><p>${feedback}</p></div>`:''}</div>${state.hints[task.id]&&!solved?`<div class="hint"><strong>Field hint</strong><p>${task.hint}</p></div>`:''}<div class="puzzle-actions">${solved?`<button class="primary" id="next">${state.task<2?'Next terminal':state.sector<5?'Collect key & continue':'Restore mainframe'} →</button>`:'<button class="primary" id="test">Test solution ↗</button><button id="hint">Request a hint</button>'}<span class="attempt-label">${state.attempts[task.id]||0} tests · No time penalty</span></div></article></section></main>`;}
function report(){const finished=done()===18;return `<main id="main" class="report-page" tabindex="-1"><div class="report-top"><div class="eyebrow">${finished?'TRANSMISSION RESTORED':'MISSION CHECKPOINT'}</div><h1>${finished?'Mainframe restored.':'Your learning report.'}</h1><p>${finished?'You challenged NULL’s assumptions and brought the crew home.':'Every repaired terminal is a step forward. You can return to the mission whenever you are ready.'}</p><div class="report-stats"><div><strong>${done()}/18</strong><span>Challenges solved</span></div><div><strong>${Game.xp(SECTORS,state)}</strong><span>Mission XP</span></div><div><strong>${Object.keys(state.hints).length}</strong><span>Hints explored</span></div></div></div><h2>Your next revision targets</h2><p>“Revisit” means you used a hint or more than one test. It is a useful practice signal, not an ability label.</p><div class="report-grid">${SECTORS.map(s=>{const complete=s.tasks.every(t=>state.solved[t.id]),revisit=s.tasks.some(t=>state.hints[t.id]||(state.attempts[t.id]||0)>1);return `<section class="report-card"><span class="eyebrow">${complete?revisit?'REVISIT':'SOLVED INDEPENDENTLY':'IN PROGRESS'}</span><h3>${s.name}</h3><ul>${s.tasks.map(t=>`<li><span>${state.solved[t.id]?'✓':'○'}</span> ${t.title}<small>${state.solved[t.id]?`${state.attempts[t.id]} test${state.attempts[t.id]===1?'':'s'}${state.hints[t.id]?' · hint used':''}`:'Not yet solved'}</small></li>`).join('')}</ul></section>`;}).join('')}</div><section class="written-practice"><span class="eyebrow">BEYOND THE GAME</span><h2>Can you explain it without the options?</h2><p>In 3–4 sentences, justify a method for investigating queues at your school. Explain one strength, one limitation and how you would address that limitation. Then evaluate whether an existing report from another school would be suitable.</p><p class="muted">This game checks recognition, application and decisions. It does not measure the quality of full exam-style written answers and cannot predict a grade.</p></section><div class="button-row"><button class="primary" id="return-game">Return to mission →</button><button id="download">Download my report</button><button id="report-reset">New mission</button></div></main>`;}
function render(focus=false){$('#app').innerHTML=view==='intro'?intro():view==='report'?report():game();$('#sound').textContent=state.sound?'Sound on':'Sound off';$('#sound').setAttribute('aria-pressed',String(state.sound));bind();if(focus)$('#main').focus();}
function loadTask(){response=state.solved[current().id]?structuredClone(current().answer):current().type==='number'?'':[];feedback=null;}
function on(selector,event,fn){const el=$(selector);if(el)el.addEventListener(event,fn);}
function bind(){
  document.querySelectorAll('[data-sector]').forEach(el=>{el.setAttribute('aria-label',SECTORS[Number(el.dataset.sector)].name);el.title=SECTORS[Number(el.dataset.sector)].name;});
  on('#start','click',()=>{state.started=true;view='game';loadTask();save();render(true);});
  on('#view-report','click',()=>{view='report';render(true);});
  on('#report','click',()=>{view='report';render(true);});
  on('#return-game','click',()=>{view='game';loadTask();render(true);});
  on('#download','click',downloadReport);on('#report-reset','click',()=>$('#reset-dialog').showModal());
  document.querySelectorAll('[data-sector]').forEach(el=>el.addEventListener('click',()=>{const i=Number(el.dataset.sector);if(!Game.unlocked(SECTORS,state,i))return;state.sector=i;const first=SECTORS[i].tasks.findIndex(t=>!state.solved[t.id]);state.task=first<0?0:first;loadTask();save();render(true);}));
  document.querySelectorAll('[data-task]').forEach(el=>el.addEventListener('click',()=>{state.task=Number(el.dataset.task);loadTask();save();render(true);}));
  document.querySelectorAll('[data-match]').forEach(el=>el.addEventListener('change',()=>{response[Number(el.dataset.match)]=el.value;}));
  document.querySelectorAll('input[name="answer"]').forEach(el=>el.addEventListener('change',()=>{response=[...document.querySelectorAll('input[name="answer"]:checked')].map(e=>Number(e.value));document.querySelectorAll('.option').forEach(label=>label.classList.toggle('selected',label.querySelector('input').checked));}));
  document.querySelectorAll('[data-order]').forEach(el=>el.addEventListener('click',()=>{response.push(Number(el.dataset.order));render();const next=document.querySelector('[data-order]:not(:disabled)')||$('#test');next?.focus();}));
  on('#undo','click',()=>{response.pop();render();$('#undo').focus();});
  on('#number-answer','input',e=>response=e.target.value);
  on('.evidence','toggle',e=>{if(e.target.open){state.inspected[current().id]=true;save();}});
  on('#command','click',()=>{$('#guide-dialog').showModal();document.getElementById('word-'+current().command).scrollIntoView({block:'center'});});
  on('#hint','click',()=>{state.hints[current().id]=true;save();render();$('#hint').focus();});
  on('#test','click',()=>{
    const task=current();
    const incomplete=task.type==='number'?String(response).trim()==='':task.type==='match'?task.rows.some((_,i)=>!response[i]):task.type==='order'?response.length!==task.options.length:task.type==='multi'?response.length!==task.answer.length:response.length!==1;
    if(incomplete){feedback=task.type==='multi'?'Select exactly two options before testing.':'Complete your answer before testing. This has not used a test.';render();$('#test').focus();return;}
    state.attempts[task.id]=(state.attempts[task.id]||0)+1;
    const correct=Game.check(task,response);tone(correct);
    if(correct){state.solved[task.id]=true;state.finished=done()===18;feedback=null;}else{feedback='Your solution does not yet fit all the evidence. Re-read the records, change your answer or request a hint.';}
    save();render();(correct?$('#next'):$('#test')).focus();
  });
  on('#next','click',()=>{if(state.task<2)state.task++;else if(state.sector<5){state.sector++;state.task=0;}else{state.finished=true;view='report';}loadTask();save();render(true);});
}
function downloadReport(){const lines=['ESCAPE THE MAINFRAME | AS ICT Chapter 1','Revision practice, not an exam grade.','',`Challenges solved: ${done()}/18`,`Mission XP: ${Game.xp(SECTORS,state)}`,''];for(const s of SECTORS){lines.push(s.name);for(const t of s.tasks){lines.push(`  ${state.solved[t.id]?'SOLVED':'NOT YET SOLVED'}: ${t.title} | tests: ${state.attempts[t.id]||0} | hint: ${state.hints[t.id]?'yes':'no'}`);if(state.solved[t.id])lines.push('  Learning point: '+t.why);}lines.push('');}lines.push('Next step: practise full written explanations, comparisons, justifications and evaluations.','This file contains no student name. Nothing has been sent to a teacher.');const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='Mainframe-learning-report.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#glossary').innerHTML=Object.entries(GLOSSARY).map(([word,meaning])=>`<dt id="word-${word}">${word}</dt><dd>${meaning}</dd>`).join('');
$('#guide').addEventListener('click',()=>$('#guide-dialog').showModal());
$('#close-guide').addEventListener('click',()=>$('#guide-dialog').close());
$('#sound').addEventListener('click',()=>{state.sound=!state.sound;save();tone(true);$('#sound').textContent=state.sound?'Sound on':'Sound off';$('#sound').setAttribute('aria-pressed',String(state.sound));});
$('#home').addEventListener('click',e=>{e.preventDefault();view='intro';render(true);});
$('#reset').addEventListener('click',()=>{$('#guide-dialog').close();$('#reset-dialog').showModal();});
$('#cancel-reset').addEventListener('click',()=>$('#reset-dialog').close());
$('#confirm-reset').addEventListener('click',()=>{state=Game.fresh();response=[];feedback=null;view='intro';save();$('#reset-dialog').close();render(true);});
if(state.started)loadTask();render();
