/* Original practice scenarios aligned to the supplied Chapter 1 knowledge bank. */
const SECTORS = [
  {name:'Raw Data Vault',short:'Data',icon:'◈',colour:'#59e5cf',desc:'Restore meaning to the station’s damaged records.',key:'CONTEXT',tasks:[
    {id:'context',type:'choice',title:'A number without a story',brief:'The terminal displays 38. Inspect the records and choose the message the engineer can act on without making an unsupported assumption.',evidence:['RAW BUFFER · 38','SENSOR LOG · coolant temperature, °C, bay B-04 at 07:45','MAINTENANCE NOTE · investigate temperatures above 35 °C'],options:['Coolant is 38 °C at bay B-04 at 07:45; the reading needs investigation because it exceeds 35 °C.','Coolant is 38 °C at bay B-04; the temperature is normal because most coolant systems tolerate 40 °C.','Coolant rose by 3 °C at 07:45; this proves the cooling system is failing.','There are 38 °C in the station; inspect every bay immediately.'],answer:[0],why:'The label, unit, place, time and threshold support the first message. No earlier reading or system limit supports the other claims.',hint:'Which message uses only the facts in the records and names the decision threshold?',command:'Explain'},
    {id:'labels',type:'match',title:'Reconnect the data dictionary',brief:'Wire each record to the label that explains it. You can change a connection before testing.',evidence:['EXPORT · 07:45 / 620 / B-04','Records are from the morning air-quality inspection.'],rows:['07:45','620','B-04'],choices:['Inspection time (HH:MM)','Carbon dioxide concentration (ppm)','Sensor location code'],answer:['Inspection time (HH:MM)','Carbon dioxide concentration (ppm)','Sensor location code'],why:'Time, measurement and location need different labels and formats. Labels make a dataset interpretable.',hint:'Look for a time format, a measurement and an identifier.',command:'Identify'},
    {id:'meaning',type:'multi',title:'The missing context',brief:'A screen says “Oxygen: 20.9”. Select the TWO additions most needed before comparing the current docking bay atmosphere with a safe range.',evidence:['The screen label identifies oxygen but gives no unit.','The technician must decide about this bay now, not the station last month.'],options:['The unit, such as percentage by volume','The sensor’s purchase price','The measurement time and location','The names of the technicians on duty','The average oxygen reading across the whole station last month'],answer:[0,2],why:'Units support a valid comparison; time and location establish whether this reading fits the current decision.',hint:'Choose details needed to interpret this value for this bay at this time.',command:'Justify'}]},
  {name:'Processing Plant',short:'Process',icon:'⚙',colour:'#a5a0ff',desc:'Turn raw readings into a useful warning.',key:'PROCESS',tasks:[
    {id:'pipeline',type:'order',title:'Rebuild the warning pipeline',brief:'Build the pipeline in the order the station should use. Cards cannot be skipped; use Undo to revise.',evidence:['INPUT · mixed dates, locations and one unverified sensor value','OUTPUT · a warning about individual readings exceeding 23 °C at this bay today'],options:['Show the engineer the highest valid reading, unit, time and warning','Compare each valid reading with the individual threshold','Select this bay’s current readings and flag suspect records for checking','Validate or exclude suspect records using the maintenance log','Calculate a mean as background context'],answer:[2,3,1,4,0],why:'Select relevant readings, check suspicious values, apply the rule to each valid reading, then add context and communicate. A mean alone cannot test an individual threshold.',hint:'Choose the relevant records first. Check the suspect sensor before applying the threshold to valid readings.',command:'Describe'},
    {id:'mean',type:'number',title:'Power the average module',brief:'Calculate the mean of the valid temperature readings for this bay today. Enter the number in °C.',evidence:['CURRENT BAY · 18, 20, 22, 24, 96 °C','MAINTENANCE LOG · the 96 °C sensor entry was marked invalid after a fault check','OTHER BAY · 26 °C; yesterday · 19 °C'],numberLabel:'Mean of valid current-bay readings (°C)',answer:21,why:'Use only 18, 20, 22 and 24 °C. Their sum is 84; 84 ÷ 4 = 21 °C. Exclude the flagged fault and irrelevant records.',hint:'Remove the invalid 96 °C value and the readings for other places or days before averaging.',command:'Calculate'},
    {id:'average',type:'choice',title:'The average is not the whole story',brief:'The valid mean is 21 °C. The rule says to investigate any individual valid reading above 23 °C. Which report is justified?',evidence:['VALID READINGS · 18, 20, 22, 24 °C','RULE · investigate individual valid readings above 23 °C','The invalid 96 °C entry has already been excluded.'],options:['The mean is below 23 °C, so report no breach; keep the 24 °C value for the next daily average.','Report the 21 °C mean as context and flag the valid 24 °C reading for investigation.','Report a 24 °C mean because the highest reading determines the average.','Investigate the 96 °C entry as a threshold breach even though the fault check ruled it invalid.'],answer:[1],why:'The 21 °C mean is useful context, but the individual 24 °C reading exceeds the rule. The invalid 96 °C entry is not a valid breach.',hint:'Distinguish the summary from the individual threshold and remember which reading was invalid.',command:'Analyse',reasonPrompt:'Explain why the mean alone cannot settle this warning.'}]},
  {name:'Source Labyrinth',short:'Sources',icon:'⌘',colour:'#ffcf73',desc:'Trace who collected the evidence and why.',key:'ORIGIN',tasks:[
    {id:'direct',type:'match',title:'Trace the collection routes',brief:'Classify each source from this investigation team’s point of view. Think about who collected it and for which purpose.',evidence:['The team is investigating this station’s docking queues today.','A document can contain first-hand observations but still be an indirect source for a different team.'],rows:['Team members count arrivals for their current investigation','The team reuses last year’s published transport-agency counts','The team sends its own questionnaire to this station’s visitors','A supplier sends the team the results of its own earlier customer survey'],choices:['Direct','Indirect'],answer:['Direct','Indirect','Direct','Indirect'],why:'Data the team collects for its investigation is direct to the team. Existing reports or a supplier’s earlier survey are indirect, even if those authors gathered their own data first-hand.',hint:'Ask whether this team collected these particular responses for this investigation.',command:'Identify'},
    {id:'dynamic',type:'match',title:'Live feed or frozen record?',brief:'Classify what each item will do after the team opens it. Consider the exact item, not the technology used to make it.',evidence:['The live dashboard refreshes from sensors; the PDF and screenshot are saved copies.','A scheduled webpage replaces its figures every hour when connected to the source.'],rows:['A PDF of the 09:00 report, opened at 14:00','A dashboard currently connected to the live sensor feed','A screenshot taken from that dashboard at 14:00','A webpage that refreshes its figures automatically each hour'],choices:['Static','Dynamic'],answer:['Static','Dynamic','Static','Dynamic'],why:'The connected dashboard and refreshing webpage change with their source. The PDF and screenshot remain snapshots, however recent they were when captured.',hint:'A recent snapshot can still be static. Ask whether this item updates automatically.',command:'Compare'},
    {id:'sourcefit',type:'multi',title:'The shortcut trap',brief:'NULL offers a report published yesterday about another spaceport. Select TWO actions that would make a staffing recommendation more defensible.',evidence:['OTHER SPACEPORT · three times larger, two arrival waves per day','THIS STATION · smaller and with one uncertain peak','DECISION · number of staff at this station tomorrow morning'],options:['Use the report as background, but check whether its population and arrival pattern transfer to this station.','Use the other site’s staffing ratio directly because it was published yesterday.','Collect or verify local queue counts over relevant periods and compare them with tomorrow’s schedule.','Ignore the report entirely because every indirect source is unsuitable.','Average the two sites’ queue sizes to remove differences in population.'],answer:[0,2],why:'A recent external report may help as background, but local demand and the relevant schedule are needed for this decision. Recency does not make populations comparable.',hint:'One action tests transferability; the other obtains relevant local evidence.',command:'Evaluate',reasonPrompt:'State one limitation of the external report and the local evidence you would seek.'}]},
  {name:'Investigation Chamber',short:'Collect',icon:'⌕',colour:'#ff9fb8',desc:'Choose methods and remove bias from your questions.',key:'METHOD',tasks:[
    {id:'methods',type:'match',title:'Equip the investigation team',brief:'Choose the strongest primary method for each aim. All four methods have a use, but each aim calls for a different one.',evidence:['The team can mix methods later; choose its first method for each stated question.'],rows:['Record temperature every minute overnight without an observer','Explore in detail why a small group struggles to book','Count the actual length of queues during a peak','Collect the same short rating from 200 visitors'],choices:['Data logging','Interview','Observation','Questionnaire'],answer:['Data logging','Interview','Observation','Questionnaire'],why:'Logging captures repeated measurements, interviews probe reasons, observation captures actual behaviour and questionnaires gather standardised responses at scale.',hint:'Match continuous measurement, depth, visible behaviour and a large standardised sample to the methods.',command:'Suggest'},
    {id:'bias',type:'choice',title:'Repair the questionnaire',brief:'NULL asks: “Don’t you agree our excellent booking system is quick and easy?” Choose the best replacement for measuring perceived booking speed.',evidence:['A separate question will investigate ease of use.','Some visitors have not used the booking system.'],options:['How would you rate the time taken to book? Very slow / Slow / Neither slow nor fast / Fast / Very fast / Not used','How satisfied were you with the speed and ease of booking? Very dissatisfied / Dissatisfied / Neutral / Satisfied / Very satisfied','How many minutes did your last booking take? 0–2 / 3–5 / 6–10 / Over 10','Was the booking time acceptable? Yes / No / Not used'],answer:[0],why:'The first item is neutral, asks only about perceived speed, uses balanced choices and accommodates non-users. The others change the aim, combine two topics or offer limited response detail.',hint:'The aim is a balanced rating of perceived speed, asked separately from ease of use.',command:'Suggest'},
    {id:'limits',type:'multi',title:'Protect the investigation',brief:'The team gets 200 replies, but almost all are from the morning shift and some misunderstood one question. Select TWO changes that address these weaknesses.',evidence:['Morning-only sampling may not represent visitors on other shifts.','Several respondents interpreted “booking time” as waiting in the physical queue.'],options:['Pilot revised wording with a small suitable group before continuing.','Add 200 more morning visitors to increase the sample size.','Include visitors from missing shifts using the same revised question.','Remove the misunderstood responses and present the rest as representative of all shifts.','Ask interviewees to estimate what visitors on other shifts would say.'],answer:[0,2],why:'Piloting checks wording and including missing shifts improves coverage. A larger biased sample does not remove the missing-shift problem.',hint:'One change repairs the question; the other repairs who was sampled.',command:'Explain',reasonPrompt:'Explain why more morning responses alone would not solve the problem.'}]},
  {name:'Evidence Reactor',short:'Judge',icon:'⏣',colour:'#92e896',desc:'Spend your evidence budget on sources that fit.',key:'JUDGEMENT',tasks:[
    {id:'evidence',type:'multi',title:'Two slots. One staffing decision.',brief:'The team has TWO evidence slots. Select the strongest pair for forecasting staff at this station tomorrow morning.',evidence:['A · consistent queue counts for this station across comparable morning peaks','B · confirmed schedule for tomorrow’s arriving vessels','C · last month’s queue counts from a larger station with different arrival patterns','D · twelve detailed interviews about how visitors feel when waiting','E · a vendor’s forecast based on an undisclosed model'],options:['A · local comparable queue counts','B · confirmed arrival schedule','C · recent counts from the larger station','D · detailed visitor interviews','E · vendor forecast with hidden method'],answer:[0,1],why:'Local comparable counts show demand during similar peaks, while the schedule indicates when tomorrow’s demand will occur. Interviews reveal experiences but cannot quantify peak staffing by themselves.',hint:'Find one source measuring actual local demand and one indicating when the next peak is expected.',command:'Justify'},
    {id:'calibrate',type:'multi',title:'The fresh-data illusion',brief:'A live sensor reports 0 °C while a second instrument reports 21 °C in the same place. Select TWO steps before basing a warning on the reading.',evidence:['Sensor calibration is overdue.','The second instrument was checked yesterday against a known reference.','The current-bay mean based on earlier valid measurements was 21 °C.'],options:['Check the sensor calibration and trace whether it has a fault.','Take the newer 0 °C value as correct because it is direct and current.','Cross-check with the independently checked instrument and repeat the measurement.','Average 0 and 21 °C and treat 10.5 °C as a verified reading.','Delete the 0 °C result without recording why it was excluded.'],answer:[0,2],why:'Direct and current readings can still be inaccurate. Check the overdue sensor and repeat or independently verify the conflicting measurement before using it.',hint:'Choose checks that establish accuracy rather than hiding or averaging the disagreement.',command:'Explain',reasonPrompt:'Explain why a live reading can still be unreliable.'},
    {id:'privacy',type:'case',title:'The tempting passenger list',brief:'Build a defensible data plan. Select the best response for each part of the decision.',evidence:['A seller offers names, contact details and travel histories from another operator.','PURPOSE · estimate this station’s queue demand by time of day.','The seller has not shown that the proposed access and use are appropriate.'],rows:['Minimum useful data for the purpose','Treatment of the seller’s personal-data offer','Practical next step for a reliable decision'],choices:['Time-banded, non-identifying local queue counts','Full travel histories in case they become useful later','Check lawful access and necessity before any personal data use','Accept the list because names improve a queue count','Collect local counts across relevant shifts using a consistent method','Rely only on the seller’s anonymous summary without checking its population'],answer:['Time-banded, non-identifying local queue counts','Check lawful access and necessity before any personal data use','Collect local counts across relevant shifts using a consistent method'],why:'The purpose needs local queue demand by time, not identities. Verify appropriate access and necessity, then gather relevant local counts consistently.',hint:'Match the data to the purpose, check whether personal data may be used and plan a relevant local collection method.',command:'Evaluate',reasonPrompt:'Why would names and travel histories add little to this staffing decision?'}]},
  {name:'NULL Core',short:'Boss',icon:'⬡',colour:'#ff7779',desc:'Break three false claims and restore the mainframe.',key:'RESTORED',tasks:[
    {id:'boss1',type:'case',title:'NULL: “First-hand means flawless.”',brief:'Break the claim by connecting classification, weakness, next evidence and justified conclusion. Each selection must play the correct role.',evidence:['The team collected its own online questionnaire.','Only morning visitors replied, but the proposed decision applies to all shifts.','Questions were piloted, but the sampling gap remains.'],rows:['Classify the team’s questionnaire','Identify its remaining limitation','Choose the evidence needed next','State the conclusion currently justified'],choices:['Direct data collected for this team’s purpose','Indirect data because it was collected online','Missing shifts may bias the findings','Piloting proves the sample represents all shifts','Responses from other shifts using the same revised question','More morning responses from the same accessible group','Findings describe the morning respondents; wider claims need a broader sample'],answer:['Direct data collected for this team’s purpose','Missing shifts may bias the findings','Responses from other shifts using the same revised question','Findings describe the morning respondents; wider claims need a broader sample'],why:'The source is direct, but piloting does not remove the sampling gap. The team must include other shifts before generalising to them.',hint:'Separate the source type from its quality, then limit your conclusion to the population actually sampled.',command:'Explain',reasonPrompt:'In your own words, rebut NULL’s claim using the sample limitation.'},
    {id:'boss2',type:'multi',title:'NULL: “Two sources always prove it.”',brief:'Two websites repeat a manufacturer’s claim that its scanner cuts queue time by 40%. Select TWO checks before recommending a purchase.',evidence:['Website 1 quotes a press release from the scanner manufacturer.','Website 2 quotes Website 1 but names no separate investigation.','The manufacturer’s trial involved a larger station with a different arrival pattern.'],options:['Trace the original figures and check whether any independent source measured the effect.','Treat the two websites as independent because their owners differ.','Check the trial method, comparison, population and potential commercial interest.','Accept the 40% figure because both webpages use the same percentage.','Apply the 40% figure to this station because newer equipment should improve queues.'],answer:[0,2],why:'Two websites can repeat one interested source. The original method, sample, context and independence matter before the figure supports a local purchase.',hint:'Ask where the 40% originated and whether the trial fits this station.',command:'Analyse',reasonPrompt:'Explain why two webpages may count as only one source of evidence.'},
    {id:'boss3',type:'case',title:'The final decision',brief:'Assemble a proportionate plan for tomorrow’s peak, including what the evidence supports, how to test it and what remains uncertain.',evidence:['Local counts across comparable days show long queues from 08:00 to 09:00.','Tomorrow’s schedule predicts a similar arrival peak.','Six interviews suggest booking confusion, but the interviewees were all from one shift.','The station can trial one extra staff member without a permanent system change.'],rows:['Immediate action supported by the strongest evidence','Measure whether the action works','Further investigation for the booking issue','Boundary on the recommendation'],choices:['Trial one extra member of staff during the predicted 08:00–09:00 peak','Replace the whole booking system now','Compare queue length and wait time during the trial with comparable peaks','Judge success by whether staff feel busier','Interview or survey visitors across shifts about the booking process','Assume six interviewees represent every visitor','Review trial results before making a permanent staffing or system change'],answer:['Trial one extra member of staff during the predicted 08:00–09:00 peak','Compare queue length and wait time during the trial with comparable peaks','Interview or survey visitors across shifts about the booking process','Review trial results before making a permanent staffing or system change'],why:'Local queue counts and the schedule support a monitored staffing trial. The limited interviews call for broader investigation, not an immediate system replacement.',hint:'Link a reversible action to the local counts, name a measurable outcome and keep the interview limitation visible.',command:'Evaluate',reasonPrompt:'Write a short recommendation with evidence, one limitation and how you will judge success.'}]}
];
const GLOSSARY = {
  Analyse:'Break the evidence into parts and explain relationships, causes or implications.',
  Assess:'Weigh relevant evidence and make a supported judgement.',
  Calculate:'Work out a numerical answer. Show working and include units when required.',
  Compare:'Make linked similarities and differences using the same feature for both items.',
  Define:'Give the precise meaning of a term.',
  Describe:'Give relevant characteristics or a clear account of what happens.',
  Discuss:'Develop relevant viewpoints or arguments, using evidence and a conclusion where appropriate.',
  Evaluate:'Weigh strengths and limitations, then give a supported judgement for the context.',
  Explain:'Make a point, give the reason or mechanism, and link it to a consequence in the context.',
  Give:'Provide the requested example, reason or item.',
  Identify:'Select or name the relevant item.',
  Justify:'Support a choice with evidence and reasons linked to the purpose.',
  State:'Give a clear, brief fact or answer.',
  Suggest:'Propose a plausible answer that fits the stated situation.'
};
if (typeof module !== 'undefined') module.exports = {SECTORS, GLOSSARY};
