/* Original practice scenarios aligned to the supplied Chapter 1 knowledge bank. */
const SECTORS = [
  {name:'Raw Data Vault',short:'Data',icon:'◈',colour:'#59e5cf',desc:'Restore meaning to the station’s damaged records.',key:'CONTEXT',tasks:[
    {id:'context',type:'choice',title:'A number without a story',brief:'The terminal displays 38. NULL claims it is useful information on its own. Inspect the records, then choose the message an engineer can act on.',evidence:['RAW BUFFER · 38','SENSOR LOG · coolant temperature, °C','MAINTENANCE NOTE · investigate temperatures above 35 °C'],options:['There are 38 people aboard the station.','Coolant is 38 °C, above the 35 °C investigation threshold.','38 is always data because it is a number.'],answer:[1],why:'The label, unit and threshold give the value meaning for the engineer. Numbers can be part of information.',hint:'Which message connects the recorded value to its field, unit and purpose?',command:'Explain'},
    {id:'labels',type:'match',title:'Reconnect the data dictionary',brief:'Wire each record to the label that explains it. You can change a connection before testing.',evidence:['EXPORT · 07:45 / 620 / B-04','Records are from the morning air-quality inspection.'],rows:['07:45','620','B-04'],choices:['Inspection time (HH:MM)','Carbon dioxide concentration (ppm)','Sensor location code'],answer:['Inspection time (HH:MM)','Carbon dioxide concentration (ppm)','Sensor location code'],why:'Time, measurement and location need different labels and formats. Labels make a dataset interpretable.',hint:'Look for a time format, a measurement and an identifier.',command:'Identify'},
    {id:'meaning',type:'multi',title:'The missing context',brief:'A screen says “Oxygen: 20.9”. Select the TWO additions most needed before a technician compares it with a safe range.',evidence:['The technician already knows the screen reports oxygen.','The task is to assess the current atmosphere in the docking bay.'],options:['The unit, such as percentage by volume','A decorative station logo','The measurement time and location','The technician’s favourite colour'],answer:[0,2],why:'Units support a valid comparison; time and location establish whether the reading is relevant to the current docking bay.',hint:'Choose details that change how the value is interpreted or whether it fits this decision.',command:'Justify'}]},
  {name:'Processing Plant',short:'Process',icon:'⚙',colour:'#a5a0ff',desc:'Turn raw readings into a useful warning.',key:'PROCESS',tasks:[
    {id:'pipeline',type:'order',title:'Rebuild the warning pipeline',brief:'Choose a card to add it to the pipeline. Use Undo if needed. Build a report for TODAY’s docking-bay temperatures.',evidence:['INPUT · readings from different days and locations','OUTPUT NEEDED · a current docking-bay heat warning'],options:['Present the average, unit, period and warning to the engineer','Calculate the mean of the selected valid temperatures','Select today’s docking-bay readings and check for missing or invalid values','Compare that mean with the specified warning threshold'],answer:[2,1,3,0],why:'First select and check relevant records, then calculate, compare and communicate. A correct calculation on the wrong records still misleads.',hint:'Before calculating, make sure you have the right records.',command:'Describe'},
    {id:'mean',type:'number',title:'Power the average module',brief:'Enter the mean temperature to restore the display. Give your answer in °C.',evidence:['VALID READINGS · 18 °C, 20 °C, 22 °C, 24 °C','All readings are from the same bay and time period.'],answer:21,why:'(18 + 20 + 22 + 24) ÷ 4 = 21 °C. A mean summarises readings, but can hide a high individual reading.',hint:'Add the four readings, then divide by four.',command:'Calculate'},
    {id:'average',type:'choice',title:'The average is not the whole story',brief:'The mean is below a 23 °C inspection threshold. NULL says no reading needs attention. What is the strongest response?',evidence:['READINGS · 18, 20, 22, 24 °C','RULE · investigate any individual reading above 23 °C'],options:['Agree: the mean replaces all individual values.','Reject the mean because averages are never useful.','Inspect the 24 °C reading; the mean can hide a threshold breach.'],answer:[2],why:'The rule applies to individual readings. The mean remains useful as a summary, but does not answer every question.',hint:'Read exactly what the rule applies to.',command:'Analyse'}]},
  {name:'Source Labyrinth',short:'Sources',icon:'⌘',colour:'#ffcf73',desc:'Trace who collected the evidence and why.',key:'ORIGIN',tasks:[
    {id:'direct',type:'match',title:'Trace the collection routes',brief:'Classify each source from the station team’s point of view. The team is investigating today’s docking queues.',evidence:['Direct: collected first-hand for this investigation.','Indirect: previously collected by someone else, often for another purpose.'],rows:['The team observes today’s docking queue','The team uses a transport agency’s existing annual report','The team sends its own online questionnaire about today’s queue'],choices:['Direct','Indirect'],answer:['Direct','Indirect','Direct'],why:'Collector and purpose decide direct versus indirect. An online questionnaire can collect direct data.',hint:'Online versus paper is not the deciding factor.',command:'Identify'},
    {id:'dynamic',type:'match',title:'Live feed or frozen record?',brief:'Route the sources to the correct terminal.',evidence:['A source can be current when saved, but still be static.','A dynamic source changes as its underlying data changes.'],rows:['A PDF of the 09:00 sensor report','A dashboard connected to a live sensor feed','A saved screenshot of that dashboard'],choices:['Static','Dynamic'],answer:['Static','Dynamic','Static'],why:'The live dashboard updates. The PDF and screenshot remain snapshots unless someone replaces them.',hint:'Will this exact source update automatically?',command:'Compare'},
    {id:'sourcefit',type:'choice',title:'The shortcut trap',brief:'NULL offers a recent report of queues at another spaceport. What is the best judgement for planning staffing at this station?',evidence:['REPORT · published yesterday','SAMPLE · a much larger spaceport with different arrival patterns'],options:['It is recent, so it must fit this station.','It may offer background, but local queue data is needed because the population and arrival patterns differ.','Indirect data can never be useful.'],answer:[1],why:'Recency is only one suitability factor. The report may be useful background without being sufficient for a local staffing decision.',hint:'Does the report describe the people and conditions in this decision?',command:'Evaluate'}]},
  {name:'Investigation Chamber',short:'Collect',icon:'⌕',colour:'#ff9fb8',desc:'Choose methods and remove bias from your questions.',key:'METHOD',tasks:[
    {id:'methods',type:'match',title:'Equip the investigation team',brief:'Choose the most suitable primary method for each mission. Each mission has a different purpose.',evidence:['Methods can be combined, but here choose the best fit for each stated task.'],rows:['Record air temperature automatically every minute overnight','Understand in detail why pilots find the booking process confusing','Count actual queue lengths without relying on people’s memory','Ask 200 visitors the same short satisfaction questions'],choices:['Data logging','Interview','Observation','Questionnaire'],answer:['Data logging','Interview','Observation','Questionnaire'],why:'Logging captures repeated measurements; interviews explore reasons; observation records behaviour; questionnaires gather standardised responses at scale.',hint:'Match frequency, depth, actual behaviour and scale to the methods.',command:'Suggest'},
    {id:'bias',type:'choice',title:'Repair the questionnaire',brief:'NULL wrote: “Don’t you agree our excellent booking system is quick and easy?” Replace it with the best first question about booking speed.',evidence:['INVESTIGATION AIM · find how visitors rate booking speed','A separate question will ask about ease of use.'],options:['How would you rate the time taken to book? Very slow / Slow / Neither slow nor fast / Fast / Very fast / Not used','Why is our brilliant booking system so fast?','Is the booking system quick and easy? Yes / No'],answer:[0],why:'The replacement is neutral, asks one thing and provides balanced choices plus a response for non-users.',hint:'Remove praise and avoid asking two things in one question.',command:'Suggest'},
    {id:'limits',type:'multi',title:'Protect the investigation',brief:'Choose TWO safeguards that address the stated risks.',evidence:['RISK 1 · one shift is missing from the sample','RISK 2 · some visitors misunderstand a question'],options:['Pilot the questions with a small suitable group, then revise unclear wording','Only survey the shift that is easiest to reach','Include visitors from the missing shift','Collect passport numbers even though the study does not need them'],answer:[0,2],why:'Piloting helps identify confusing wording; sampling the missing shift improves coverage. Unnecessary identifiers add privacy risk without helping the stated aim.',hint:'Choose one safeguard for each risk, not just more data.',command:'Explain'}]},
  {name:'Evidence Reactor',short:'Judge',icon:'⏣',colour:'#92e896',desc:'Spend your evidence budget on sources that fit.',key:'JUDGEMENT',tasks:[
    {id:'evidence',type:'multi',title:'Two slots. One staffing decision.',brief:'You have TWO evidence slots. Pick the strongest pair for deciding how many staff are needed at THIS station at peak times.',evidence:['A · queue counts this week, all shifts, recorded with a consistent method','B · this week’s station arrival schedule','C · an equipment seller’s claim: “Our scanner removes every queue”','D · a ten-year-old report from a larger station'],options:['A · local queue counts','B · current arrival schedule','C · seller’s claim','D · old report elsewhere'],answer:[0,1],why:'Local queue counts show actual demand; the arrival schedule helps explain peaks and plan cover. Check limitations and unexpected events before deciding.',hint:'Combine evidence of actual queues with relevant evidence of when demand occurs.',command:'Justify'},
    {id:'calibrate',type:'choice',title:'The fresh-data illusion',brief:'The live sensor says 0 °C. NULL says it must be correct because it is direct and current. What should the team do?',evidence:['MAINTENANCE LOG · sensor calibration check overdue','SECOND INSTRUMENT · reads 21 °C in the same location'],options:['Trust the live reading without checking.','Check calibration and compare with a reliable instrument before using the reading.','Average 0 and 21 and assume the result is correct.'],answer:[1],why:'Direct and current do not guarantee accuracy. The conflicting instrument reading and overdue calibration justify investigation, not blind averaging.',hint:'Freshness does not repair a faulty measurement method.',command:'Explain'},
    {id:'privacy',type:'choice',title:'The tempting passenger list',brief:'A seller offers names, travel histories and contact details. The station only needs anonymous queue counts. Choose the defensible action.',evidence:['PURPOSE · estimate queue demand','The seller has not demonstrated lawful, appropriate access or use.'],options:['Buy everything because more data always improves a decision.','Publish the list so everyone can analyse it.','Use appropriate non-identifying queue data; check lawful access, purpose and necessity before using third-party personal data.'],answer:[2],why:'Suitability includes lawful and ethical use. Extra personal data is not justified simply because it is available.',hint:'Ask what data the decision actually needs.',command:'Evaluate'}]},
  {name:'NULL Core',short:'Boss',icon:'⬡',colour:'#ff7779',desc:'Break three false claims and restore the mainframe.',key:'RESTORED',tasks:[
    {id:'boss1',type:'choice',title:'NULL: “First-hand means flawless.”',brief:'Choose the counterargument that combines a correct principle with evidence from this mission.',evidence:['The team collected its own questionnaire online.','Only morning visitors replied, but the decision covers all shifts.'],options:['Online data is always indirect.','It is direct, but missing shifts can bias the results, so expand coverage before generalising.','It is direct, so the result represents every shift.'],answer:[1],why:'Being first-hand does not remove sampling bias. The source is direct, but the missing shifts limit the conclusion.',hint:'Source classification and quality are separate judgements.',command:'Explain'},
    {id:'boss2',type:'multi',title:'NULL: “Two sources always prove it.”',brief:'Select TWO checks needed before treating two reports as independent support.',evidence:['Two websites repeat an identical queue-reduction claim.','Both cite the same scanner manufacturer.'],options:['Trace the original evidence and check whether the reports are independent','Count the number of websites and ignore their sources','Check the method, sample, relevance and potential commercial bias','Assume matching wording guarantees accuracy'],answer:[0,2],why:'Repeating one interested source is not independent corroboration. Cross-check relevant evidence and how it was produced.',hint:'Two webpages can still contain only one original source.',command:'Analyse'},
    {id:'boss3',type:'choice',title:'The final decision',brief:'The crew needs a plan for tomorrow’s peak docking period. Choose the strongest supported judgement to shut down NULL.',evidence:['Consistent local observations show long queues at 08:00–09:00 across all shifts sampled this week.','Tomorrow’s schedule predicts another arrival peak then.','A few interviews suggest booking confusion, but the sample is small.'],options:['Replace the entire booking system immediately because a few interviewees disliked it.','Trial extra cover at the predicted peak, monitor queues, and investigate booking confusion with a broader sample before a major system change.','Make no change because evidence can never be perfect.'],answer:[1],why:'The trial uses two relevant sources, acknowledges the interview limitation and includes monitoring. Evaluation ends in a supported, proportionate judgement.',hint:'Use the strongest evidence, acknowledge uncertainty and check the result.',command:'Evaluate'}]}
];
const GLOSSARY = {
  Analyse:'Break the evidence into parts and explain relationships, causes or implications.',
  Assess:'Weigh relevant evidence and make a supported judgement.',
  Calculate:'Work out a numerical answer. Show working and include units when required.',
  Compare:'Make linked similarities and differences using the same feature for both items.',
  Define:'Give the precise meaning of a term.',
  Describe:'Give relevant characteristics or a clear account of what happens.',
  Discuss:'Develop relevant viewpoints or arguments, using evidence and a conclusion where appropriate.',
  Evaluate:'Weigh strengths and limitations, then give a supported judgement for the context.',
  Explain:'Make a point, give the reason or mechanism, and link it to a consequence in the context.',
  Give:'Provide the requested example, reason or item.',
  Identify:'Select or name the relevant item.',
  Justify:'Support a choice with evidence and reasons linked to the purpose.',
  State:'Give a clear, brief fact or answer.',
  Suggest:'Propose a plausible answer that fits the stated situation.'
};
if (typeof module !== 'undefined') module.exports = {SECTORS, GLOSSARY};
